# Production: Full resources
# NOTE: Only AuthService and Frontend CRDs have a resources field.
# IdentityService, UserService, BlogService CRDs do not support spec.resources.
# TODO: Add resources field to remaining CRDs in the operator
apiVersion: apps.example.com/v1alpha1
kind: AuthService
metadata:
  name: auth-service
spec:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
---
apiVersion: apps.example.com/v1alpha1
kind: Frontend
metadata:
  name: auth-frontend
spec:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
