# Production: Full resources
# NOTE: Only Frontend CRD has a resources field.
# IdentityService, UserService, BlogService CRDs do not support spec.resources.
# TODO: Add resources field to remaining CRDs in the operator
apiVersion: apps.example.com/v1alpha1
kind: Frontend
metadata:
  name: auth-frontend
spec:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
---
# Phase 5: Media Processing Platform
apiVersion: apps.example.com/v1alpha1
kind: MediaApiService
metadata:
  name: media-api
spec:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
---
apiVersion: apps.example.com/v1alpha1
kind: ImageWorker
metadata:
  name: image-worker
spec:
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
---
apiVersion: apps.example.com/v1alpha1
kind: VideoWorker
metadata:
  name: video-worker
spec:
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
---
apiVersion: apps.example.com/v1alpha1
kind: AudioWorker
metadata:
  name: audio-worker
spec:
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
---
apiVersion: apps.example.com/v1alpha1
kind: DocumentWorker
metadata:
  name: document-worker
spec:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
---
apiVersion: apps.example.com/v1alpha1
kind: ArchiveWorker
metadata:
  name: archive-worker
spec:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
---
apiVersion: apps.example.com/v1alpha1
kind: UploadService
metadata:
  name: upload-service
spec:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
