apiVersion: apps.example.com/v1alpha1
kind: UserService
metadata:
  name: user-service
spec:
  serviceName: user-service
  image: 939217651725.dkr.ecr.eu-west-2.amazonaws.com/kubeadm_ec2_cluster/user-service:v5-58f5af9
  replicas: 1
  port: 3001
  serviceType: ClusterIP
  
  # PostgreSQL configuration
  postgres:
    enabled: true
    database: users
    user: userservice
    password: change-in-production
  
  # Kafka configuration
  kafka:
    enabled: true
    brokers:
      - "platform-kafka-kafka-bootstrap.kafka:9092"
    consumerGroupId: "user-consumer-group"
    topics:
      identityEvents: "identity.events"
      userEvents: "user.events"
    eventHandlers: '{"identity.events":{"identity.created":"CreateProfileUseCase"}}'
