apiVersion: apps.example.com/v1alpha1
kind: UserService
metadata:
  name: user-service
spec:
  serviceName: user-service
  image: healthxcape/user-service:v1.0.0
  replicas: 1
  port: 3001
  serviceType: ClusterIP
  
  # PostgreSQL configuration
  postgres:
    enabled: true
    database: users
    user: userservice
    passwordSecret: user-postgres-secret
  
  # Kafka configuration
  kafka:
    enabled: true
    brokers:
      - "my-cluster-kafka-bootstrap.kafka:9092"
    consumerGroup: "user-service-group"
    topics:
      consume:
        - "identity.events"
      produce:
        - "user.events"
  
  # Health check
  healthCheck:
    path: /profiles/health
    port: 3001
