apiVersion: apps.example.com/v1alpha1
kind: IdentityService
metadata:
  name: identity-service
spec:
  serviceName: identity-service
  image: 939217651725.dkr.ecr.eu-west-2.amazonaws.com/kubeadm_ec2_cluster/identity-service:v5-58f5af9
  replicas: 1
  port: 3000
  serviceType: ClusterIP
  
  # PostgreSQL configuration
  postgres:
    enabled: true
    database: identity
    user: identity
    password: change-in-production
  
  # Redis configuration
  redis:
    enabled: true
  
  # Kafka configuration
  kafka:
    enabled: true
    brokers:
      - "platform-kafka-kafka-bootstrap.kafka:9092"
    topics:
      identityEvents: "identity.events"
      userEvents: "user.events"
  
  # JWT configuration
  jwt:
    secret: "platform-jwt-secret"
    accessTokenTtl: 900
    refreshTokenTtl: 604800
