apiVersion: apps.example.com/v1alpha1
kind: KafkaCluster
metadata:
  name: platform-kafka
  namespace: kafka
spec:
  clusterName: platform-kafka
  namespace: kafka
  
  # KRaft mode (no ZooKeeper)
  kraft:
    enabled: true
  
  # Kafka configuration (nested under kafka: to match CRD schema)
  kafka:
    version: "4.0.0"
    replicas: 2
    
    # Storage configuration - EBS CSI dynamic provisioning
    storage:
      type: persistent-claim
      size: 10Gi
      storageClass: "ebs-gp3"
      deleteClaim: false
    
    # Listener configuration
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    
    # Kafka broker config for staging (2 brokers)
    config:
      default.replication.factor: 2
      min.insync.replicas: 1
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      log.retention.hours: 168
      num.partitions: 3
    
    # Resource limits - optimized for staging
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  
  # Platform topics with replication
  topics:
    - name: identity.events
      partitions: 3
      replicas: 2
      config:
        retention.ms: "604800000"
    - name: user.events
      partitions: 3
      replicas: 2
      config:
        retention.ms: "604800000"
    - name: blog.events
      partitions: 3
      replicas: 2
      config:
        retention.ms: "604800000"
    - name: platform-dlq
      partitions: 3
      replicas: 2
      config:
        retention.ms: "2592000000"
