---
# Native Strimzi KafkaNodePool for broker/controller nodes
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: platform-kafka
spec:
  replicas: 2
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"
---
# Native Strimzi Kafka cluster (KRaft mode)
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: platform-kafka
  namespace: kafka
  annotations:
    strimzi.io/kraft: "enabled"
    strimzi.io/node-pools: "enabled"
spec:
  kafka:
    version: "4.0.0"
    metadataVersion: "4.0-IV0"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      default.replication.factor: 2
      min.insync.replicas: 1
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      log.retention.hours: 168
      num.partitions: 3
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
# Platform Topics
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: identity.events
  namespace: kafka
  labels:
    strimzi.io/cluster: platform-kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: "604800000"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: user.events
  namespace: kafka
  labels:
    strimzi.io/cluster: platform-kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: "604800000"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: blog.events
  namespace: kafka
  labels:
    strimzi.io/cluster: platform-kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: "604800000"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: platform-dlq
  namespace: kafka
  labels:
    strimzi.io/cluster: platform-kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: "2592000000"
