apiVersion: apps.example.com/v1alpha1
kind: KafkaCluster
metadata:
  name: platform-kafka
  namespace: kafka
spec:
  clusterName: platform-kafka
  namespace: kafka
  
  # Kafka version (Strimzi 0.44+ / Kafka 4.0)
  version: "4.0.0"
  
  # Replicas: 2 for staging (HA with resource constraints)
  replicas: 2
  
  # Storage configuration - PERSISTENT for staging
  storage:
    type: persistent-claim
    size: 10Gi
    storageClass: ""  # Uses default or manual PVs
    deleteClaim: false  # Keep data on cluster deletion
  
  # Listener configuration
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
  
  # KRaft mode (no ZooKeeper)
  kraft:
    enabled: true
  
  # Kafka config for staging (2 brokers)
  config:
    default.replication.factor: 2
    min.insync.replicas: 1
    offsets.topic.replication.factor: 2
    transaction.state.log.replication.factor: 2
    transaction.state.log.min.isr: 1
    log.retention.hours: 168  # 7 days
    num.partitions: 3
  
  # Platform topics with replication
  topics:
    - name: identity.events
      partitions: 3
      replicas: 2
      config:
        retention.ms: "604800000"  # 7 days
    - name: user.events
      partitions: 3
      replicas: 2
      config:
        retention.ms: "604800000"
    - name: blog.events
      partitions: 3
      replicas: 2
      config:
        retention.ms: "604800000"
    - name: platform-dlq
      partitions: 3
      replicas: 2
      config:
        retention.ms: "2592000000"  # 30 days
  
  # Resource limits - optimized for staging
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"
