apiVersion: apps.example.com/v1alpha1
kind: Frontend
metadata:
  name: auth-frontend
spec:
  serviceName: auth-frontend
  image: 939217651725.dkr.ecr.eu-west-2.amazonaws.com/kubeadm_ec2_cluster/frontend:v1.1.0
  replicas: 3
  port: 3000
  serviceType: ClusterIP
  
  # Auth API URL (legacy field - maps to identity-service)
  authApiUrl: "http://identity-service:3000"
  
  # Backend service URLs (internal cluster DNS)
  backendServices:
    identityService: "http://identity-service:3000"
    userService: "http://user-service:3001"
    blogService: "http://blog-service:3002"
  
  # Environment variables
  env:
    - name: NODE_ENV
      value: production
    - name: NEXT_PUBLIC_API_URL
      value: ""
  
  # Health check
  healthCheck:
    path: /
    port: 3000
