apiVersion: apps.example.com/v1alpha1
kind: Frontend
metadata:
  name: auth-frontend
spec:
  serviceName: auth-frontend
  image: 939217651725.dkr.ecr.eu-west-2.amazonaws.com/kubeadm_ec2_cluster/frontend:v5-58f5af9
  replicas: 1
  port: 3000
  
  # Auth API URL (legacy field - maps to identity-service)
  authApiUrl: "http://identity-service:3000"
