apiVersion: apps.example.com/v1alpha1
kind: Frontend
metadata:
  name: auth-frontend
spec:
  serviceName: auth-frontend
  image: frontend:latest
  replicas: 1
  port: 3000
  serviceType: ClusterIP
  
  # Backend service URLs (internal cluster DNS)
  backendServices:
    identityService: "http://identity-service:3000"
    userService: "http://user-service:3001"
    blogService: "http://blog-service:3002"
  
  # Environment variables
  env:
    - name: NODE_ENV
      value: production
    - name: NEXT_PUBLIC_API_URL
      value: ""
  
  # Health check
  healthCheck:
    path: /
    port: 3000
