apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webapp-operator-manager-role
rules:
  # Core resources
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Namespaces - cross-namespace watching and kafka namespace creation
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Events - status reporting
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  # Deployments and StatefulSets
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Custom Resources - apps.example.com
  - apiGroups:
      - apps.example.com
    resources:
      - webapps
      - webapps/status
      - webapps/finalizers
      - authservices
      - authservices/status
      - authservices/finalizers
      - frontends
      - frontends/status
      - frontends/finalizers
      - identityservices
      - identityservices/status
      - identityservices/finalizers
      - userservices
      - userservices/status
      - userservices/finalizers
      - blogservices
      - blogservices/status
      - blogservices/finalizers
      - kafkaclusters
      - kafkaclusters/status
      - kafkaclusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Strimzi Kafka resources
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkatopics
      - kafkausers
      - kafkanodepools
      - kafkaconnects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # CRDs - needed for Strimzi operator installation
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  # RBAC - needed for Strimzi operator installation
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - bind
      - escalate
  # Network policies
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Batch jobs - for Strimzi
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
