apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webapp-operator-manager-role
rules:
  # Core resources
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Deployments and StatefulSets
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Custom Resources - apps.example.com
  - apiGroups:
      - apps.example.com
    resources:
      - webapps
      - webapps/status
      - webapps/finalizers
      - authservices
      - authservices/status
      - authservices/finalizers
      - frontends
      - frontends/status
      - frontends/finalizers
      - identityservices
      - identityservices/status
      - identityservices/finalizers
      - userservices
      - userservices/status
      - userservices/finalizers
      - blogservices
      - blogservices/status
      - blogservices/finalizers
      - kafkaclusters
      - kafkaclusters/status
      - kafkaclusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Strimzi Kafka resources
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkatopics
      - kafkausers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # RBAC
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
