apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp-operator-leader-election-rolebinding
  namespace: platform-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webapp-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: webapp-operator-controller-manager
    namespace: platform-system
