apiVersion: apps.example.com/v1alpha1
kind: BlogService
metadata:
  name: blog-service
spec:
  serviceName: blog-service
  image: 939217651725.dkr.ecr.eu-west-2.amazonaws.com/kubeadm_ec2_cluster/blog-service:v1.1.0
  replicas: 1
  port: 3002
  serviceType: ClusterIP
  
  # PostgreSQL configuration
  postgres:
    enabled: true
    database: blog
    user: blogservice
    passwordSecret: blog-postgres-secret
  
  # Kafka configuration
  kafka:
    enabled: true
    brokers:
      - "platform-kafka-kafka-bootstrap.kafka:9092"
    consumerGroupId: "blog-service-group"
    topics:
      blogEvents: "blog.events"
      userEvents: "user.events"
  
  # Health check
  healthCheck:
    path: /api/v1/health
    port: 3002
