---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: userservices.apps.example.com
spec:
  group: apps.example.com
  scope: Namespaced
  names:
    plural: userservices
    singular: userservice
    kind: UserService
    listKind: UserServiceList
    shortNames:
      - usersvc
      - profile
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
              properties:
                serviceName:
                  type: string
                  default: user-service
                  description: "Name of the user service (Profile bounded context)"
                image:
                  type: string
                  description: "Container image (e.g., user-service:v1.0.0)"
                replicas:
                  type: integer
                  default: 1
                  minimum: 1
                port:
                  type: integer
                  default: 3001
                serviceType:
                  type: string
                  enum: ["ClusterIP", "NodePort", "LoadBalancer"]
                  default: "NodePort"
                nodePort:
                  type: integer
                  minimum: 30000
                  maximum: 32767
                # PostgreSQL for UserProfile storage
                postgres:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    image:
                      type: string
                      default: "postgres:15-alpine"
                    database:
                      type: string
                      default: "userprofile"
                    user:
                      type: string
                      default: "userprofile"
                    password:
                      type: string
                      default: "userprofile123"
                    storageSize:
                      type: string
                      default: "1Gi"
                # Kafka configuration for event-driven messaging
                kafka:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    brokers:
                      type: array
                      items:
                        type: string
                    clientId:
                      type: string
                    consumerGroupId:
                      type: string
                    topics:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    eventHandlers:
                      type: string
                      description: "JSON mapping of topic.event to handler"
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Image
          type: string
          jsonPath: .spec.image
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
