---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authservices.apps.example.com
spec:
  group: apps.example.com
  scope: Namespaced
  names:
    plural: authservices
    singular: authservice
    kind: AuthService
    listKind: AuthServiceList
    shortNames:
      - auth
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
              properties:
                serviceName:
                  type: string
                  default: auth-service
                  description: "Name of the auth service"
                image:
                  type: string
                  description: "Container image (e.g., auth-service:v1.0.0)"
                replicas:
                  type: integer
                  default: 1
                  minimum: 1
                port:
                  type: integer
                  default: 3000
                serviceType:
                  type: string
                  enum: ["ClusterIP", "NodePort", "LoadBalancer"]
                  default: "NodePort"
                nodePort:
                  type: integer
                  minimum: 30000
                  maximum: 32767
                postgres:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    image:
                      type: string
                      default: "postgres:15-alpine"
                    database:
                      type: string
                      default: "authdb"
                    username:
                      type: string
                      default: "postgres"
                    password:
                      type: string
                      default: "pass123"
                redis:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    image:
                      type: string
                      default: "redis:7-alpine"
                jwt:
                  type: object
                  properties:
                    secret:
                      type: string
                      default: "your-secret-key"
                    accessTokenTtl:
                      type: string
                      default: "3600"
                    refreshTokenTtl:
                      type: string
                      default: "86400"
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                postgresReady:
                  type: string
                redisReady:
                  type: string
                message:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Image
          type: string
          jsonPath: .spec.image
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
