# Development: Override spec.image for minikube local Docker images
# Kustomize images transformer does NOT work on CRD custom fields (spec.image).
# Strategic merge patches target each CR by kind+name to set the correct local tag.
apiVersion: apps.example.com/v1alpha1
kind: IdentityService
metadata:
  name: identity-service
spec:
  image: identity-service:v1.0.5
---
apiVersion: apps.example.com/v1alpha1
kind: AuthService
metadata:
  name: auth-service
spec:
  image: auth-service:v1.0.0
---
apiVersion: apps.example.com/v1alpha1
kind: UserService
metadata:
  name: user-service
spec:
  image: user-service:v1.0.4
---
apiVersion: apps.example.com/v1alpha1
kind: BlogService
metadata:
  name: blog-service
spec:
  image: blog-service:v1.0.5
---
apiVersion: apps.example.com/v1alpha1
kind: Frontend
metadata:
  name: auth-frontend
spec:
  image: frontend:v1.0.2
